import Head from 'next/head'
import Link from 'next/link'
import useSWR from 'swr'
import Header from '../components/Header'
import Snippet from '../components/Snippet'

export default function Home() {
  const { data: snippets, mutate } = useSWR('/api/snippets')
  return (
    <div>
      <Head>
        <title>Snippet App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="my-12">
          <Header
            title="Snippets App"
            subtitle="Create and browse snippets in web development"
          />
        </div>
        {
          snippets &&
          snippets.map((snippet) => (
            <Snippet
              key={snippet.id}
              snippet={snippet}
              snippetDeleted={mutate}
            />
          ))
        }
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
