import Head from 'next/head'
import Link from 'next/link'
import useSWR from 'swr'
import Snippet from '../components/Snippet'

export default function Home() {
  const { data: snippets, mutate } = useSWR('/api/snippets')
  return (
    <div>
      <Head>
        <title>Snippet App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="my-12">
          <h1 className="text-purple-100 text-2xl">
            Snippet App
          </h1>
          <p className="text-purple-200">
            Create and browse snippets in Web Development!
          </p>
          <Link href="/new">
            <a className="mt-3 inline-block bg-purple-900 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
              Create a Snippet!
            </a>
          </Link>
        </div>
        {
          snippets &&
          snippets.map((snippet) => (
            <Snippet
              key={snippet.id}
              snippet={snippet}
              snippetDeleted={mutate}
            />
          ))
        }
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
